// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/api/knn.proto

package knnpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KNN_GetServers_FullMethodName = "/knn.KNN/getServers"
	KNN_GetKNN_FullMethodName     = "/knn.KNN/GetKNN"
)

// KNNClient is the client API for KNN service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KNNClient interface {
	GetServers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Servers, error)
	GetKNN(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Distances, error)
}

type kNNClient struct {
	cc grpc.ClientConnInterface
}

func NewKNNClient(cc grpc.ClientConnInterface) KNNClient {
	return &kNNClient{cc}
}

func (c *kNNClient) GetServers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Servers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Servers)
	err := c.cc.Invoke(ctx, KNN_GetServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kNNClient) GetKNN(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Distances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Distances)
	err := c.cc.Invoke(ctx, KNN_GetKNN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KNNServer is the server API for KNN service.
// All implementations must embed UnimplementedKNNServer
// for forward compatibility.
type KNNServer interface {
	GetServers(context.Context, *Empty) (*Servers, error)
	GetKNN(context.Context, *Query) (*Distances, error)
	mustEmbedUnimplementedKNNServer()
}

// UnimplementedKNNServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKNNServer struct{}

func (UnimplementedKNNServer) GetServers(context.Context, *Empty) (*Servers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServers not implemented")
}
func (UnimplementedKNNServer) GetKNN(context.Context, *Query) (*Distances, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKNN not implemented")
}
func (UnimplementedKNNServer) mustEmbedUnimplementedKNNServer() {}
func (UnimplementedKNNServer) testEmbeddedByValue()             {}

// UnsafeKNNServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KNNServer will
// result in compilation errors.
type UnsafeKNNServer interface {
	mustEmbedUnimplementedKNNServer()
}

func RegisterKNNServer(s grpc.ServiceRegistrar, srv KNNServer) {
	// If the following call pancis, it indicates UnimplementedKNNServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KNN_ServiceDesc, srv)
}

func _KNN_GetServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KNNServer).GetServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KNN_GetServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KNNServer).GetServers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KNN_GetKNN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KNNServer).GetKNN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KNN_GetKNN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KNNServer).GetKNN(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

// KNN_ServiceDesc is the grpc.ServiceDesc for KNN service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KNN_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knn.KNN",
	HandlerType: (*KNNServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getServers",
			Handler:    _KNN_GetServers_Handler,
		},
		{
			MethodName: "GetKNN",
			Handler:    _KNN_GetKNN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/knn.proto",
}
