// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: pkg/proto/state.proto

package spb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RideInfo_Status int32

const (
	RideInfo_PENDING              RideInfo_Status = 0 // request has gone to the driver, he has not pressed y/n yet.
	RideInfo_IN_PROGRESS          RideInfo_Status = 1 // driver accepted, ongoing ride
	RideInfo_NO_DRIVERS_AVAILABLE RideInfo_Status = 2 // all denied, or all occupied, or none connected
	RideInfo_COMPLETED            RideInfo_Status = 3 // driver has marked ride completed via  completeride rpc
)

// Enum value maps for RideInfo_Status.
var (
	RideInfo_Status_name = map[int32]string{
		0: "PENDING",
		1: "IN_PROGRESS",
		2: "NO_DRIVERS_AVAILABLE",
		3: "COMPLETED",
	}
	RideInfo_Status_value = map[string]int32{
		"PENDING":              0,
		"IN_PROGRESS":          1,
		"NO_DRIVERS_AVAILABLE": 2,
		"COMPLETED":            3,
	}
)

func (x RideInfo_Status) Enum() *RideInfo_Status {
	p := new(RideInfo_Status)
	*p = x
	return p
}

func (x RideInfo_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RideInfo_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_state_proto_enumTypes[0].Descriptor()
}

func (RideInfo_Status) Type() protoreflect.EnumType {
	return &file_pkg_proto_state_proto_enumTypes[0]
}

func (x RideInfo_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RideInfo_Status.Descriptor instead.
func (RideInfo_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_state_proto_rawDescGZIP(), []int{2, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_proto_state_proto_rawDescGZIP(), []int{0}
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State  []*RideInfo `protobuf:"bytes,1,rep,name=state,proto3" json:"state,omitempty"`
	Server string      `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"` // server calling the StateService
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_pkg_proto_state_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetState() []*RideInfo {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *State) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type RideInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiderId     string          `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId    string          `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Pickup      string          `protobuf:"bytes,3,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Destination string          `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Status      RideInfo_Status `protobuf:"varint,5,opt,name=status,proto3,enum=myuber.RideInfo_Status" json:"status,omitempty"`
}

func (x *RideInfo) Reset() {
	*x = RideInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideInfo) ProtoMessage() {}

func (x *RideInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideInfo.ProtoReflect.Descriptor instead.
func (*RideInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_state_proto_rawDescGZIP(), []int{2}
}

func (x *RideInfo) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RideInfo) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *RideInfo) GetPickup() string {
	if x != nil {
		return x.Pickup
	}
	return ""
}

func (x *RideInfo) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RideInfo) GetStatus() RideInfo_Status {
	if x != nil {
		return x.Status
	}
	return RideInfo_PENDING
}

var File_pkg_proto_state_proto protoreflect.FileDescriptor

var file_pkg_proto_state_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x79, 0x75, 0x62, 0x65, 0x72, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x47, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6d, 0x79, 0x75, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x22, 0xfe, 0x01, 0x0a, 0x08, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x6d, 0x79, 0x75, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x4f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50,
	0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4e, 0x4f, 0x5f,
	0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x53, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c,
	0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44,
	0x10, 0x03, 0x32, 0x66, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0d,
	0x2e, 0x6d, 0x79, 0x75, 0x62, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e,
	0x6d, 0x79, 0x75, 0x62, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x2a,
	0x0a, 0x08, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x6d, 0x79, 0x75,
	0x62, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x0d, 0x2e, 0x6d, 0x79, 0x75, 0x62,
	0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x3b, 0x73, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_state_proto_rawDescOnce sync.Once
	file_pkg_proto_state_proto_rawDescData = file_pkg_proto_state_proto_rawDesc
)

func file_pkg_proto_state_proto_rawDescGZIP() []byte {
	file_pkg_proto_state_proto_rawDescOnce.Do(func() {
		file_pkg_proto_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_state_proto_rawDescData)
	})
	return file_pkg_proto_state_proto_rawDescData
}

var file_pkg_proto_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_state_proto_goTypes = []any{
	(RideInfo_Status)(0), // 0: myuber.RideInfo.Status
	(*Empty)(nil),        // 1: myuber.Empty
	(*State)(nil),        // 2: myuber.State
	(*RideInfo)(nil),     // 3: myuber.RideInfo
}
var file_pkg_proto_state_proto_depIdxs = []int32{
	3, // 0: myuber.State.state:type_name -> myuber.RideInfo
	0, // 1: myuber.RideInfo.status:type_name -> myuber.RideInfo.Status
	1, // 2: myuber.StateService.GetState:input_type -> myuber.Empty
	2, // 3: myuber.StateService.SetState:input_type -> myuber.State
	2, // 4: myuber.StateService.GetState:output_type -> myuber.State
	1, // 5: myuber.StateService.SetState:output_type -> myuber.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_state_proto_init() }
func file_pkg_proto_state_proto_init() {
	if File_pkg_proto_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_state_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_state_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_state_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RideInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_state_proto_goTypes,
		DependencyIndexes: file_pkg_proto_state_proto_depIdxs,
		EnumInfos:         file_pkg_proto_state_proto_enumTypes,
		MessageInfos:      file_pkg_proto_state_proto_msgTypes,
	}.Build()
	File_pkg_proto_state_proto = out.File
	file_pkg_proto_state_proto_rawDesc = nil
	file_pkg_proto_state_proto_goTypes = nil
	file_pkg_proto_state_proto_depIdxs = nil
}
