// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: pkg/proto/labyrinth.proto

package lrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Move_Direction int32

const (
	Move_UP    Move_Direction = 0
	Move_DOWN  Move_Direction = 1
	Move_LEFT  Move_Direction = 2
	Move_RIGHT Move_Direction = 3
)

// Enum value maps for Move_Direction.
var (
	Move_Direction_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "LEFT",
		3: "RIGHT",
	}
	Move_Direction_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"LEFT":  2,
		"RIGHT": 3,
	}
)

func (x Move_Direction) Enum() *Move_Direction {
	p := new(Move_Direction)
	*p = x
	return p
}

func (x Move_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Move_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_labyrinth_proto_enumTypes[0].Descriptor()
}

func (Move_Direction) Type() protoreflect.EnumType {
	return &file_pkg_proto_labyrinth_proto_enumTypes[0]
}

func (x Move_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Move_Direction.Descriptor instead.
func (Move_Direction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{4, 0}
}

type MoveResponse_Status int32

const (
	MoveResponse_SUCCESS MoveResponse_Status = 0
	MoveResponse_FAILURE MoveResponse_Status = 1
	MoveResponse_VICTORY MoveResponse_Status = 2
	MoveResponse_DEATH   MoveResponse_Status = 3
)

// Enum value maps for MoveResponse_Status.
var (
	MoveResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
		2: "VICTORY",
		3: "DEATH",
	}
	MoveResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
		"VICTORY": 2,
		"DEATH":   3,
	}
)

func (x MoveResponse_Status) Enum() *MoveResponse_Status {
	p := new(MoveResponse_Status)
	*p = x
	return p
}

func (x MoveResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_labyrinth_proto_enumTypes[1].Descriptor()
}

func (MoveResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_proto_labyrinth_proto_enumTypes[1]
}

func (x MoveResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveResponse_Status.Descriptor instead.
func (MoveResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{5, 0}
}

type RevelioRequest_Tile int32

const (
	RevelioRequest_EMPTY RevelioRequest_Tile = 0
	RevelioRequest_COIN  RevelioRequest_Tile = 1
	RevelioRequest_WALL  RevelioRequest_Tile = 2
)

// Enum value maps for RevelioRequest_Tile.
var (
	RevelioRequest_Tile_name = map[int32]string{
		0: "EMPTY",
		1: "COIN",
		2: "WALL",
	}
	RevelioRequest_Tile_value = map[string]int32{
		"EMPTY": 0,
		"COIN":  1,
		"WALL":  2,
	}
)

func (x RevelioRequest_Tile) Enum() *RevelioRequest_Tile {
	p := new(RevelioRequest_Tile)
	*p = x
	return p
}

func (x RevelioRequest_Tile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RevelioRequest_Tile) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_labyrinth_proto_enumTypes[2].Descriptor()
}

func (RevelioRequest_Tile) Type() protoreflect.EnumType {
	return &file_pkg_proto_labyrinth_proto_enumTypes[2]
}

func (x RevelioRequest_Tile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RevelioRequest_Tile.Descriptor instead.
func (RevelioRequest_Tile) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{6, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{0}
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type LabyrinthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int32 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width  int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *LabyrinthInfo) Reset() {
	*x = LabyrinthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabyrinthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabyrinthInfo) ProtoMessage() {}

func (x *LabyrinthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabyrinthInfo.ProtoReflect.Descriptor instead.
func (*LabyrinthInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{2}
}

func (x *LabyrinthInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *LabyrinthInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type PlayerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score    int32     `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Health   int32     `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	Position *Position `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Spells   int32     `protobuf:"varint,4,opt,name=spells,proto3" json:"spells,omitempty"` // remaining spells
}

func (x *PlayerStatus) Reset() {
	*x = PlayerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatus) ProtoMessage() {}

func (x *PlayerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatus.ProtoReflect.Descriptor instead.
func (*PlayerStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerStatus) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerStatus) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerStatus) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerStatus) GetSpells() int32 {
	if x != nil {
		return x.Spells
	}
	return 0
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction Move_Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=labyrinth.Move_Direction" json:"direction,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{4}
}

func (x *Move) GetDirection() Move_Direction {
	if x != nil {
		return x.Direction
	}
	return Move_UP
}

type MoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status MoveResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=labyrinth.MoveResponse_Status" json:"status,omitempty"`
	Wall   bool                `protobuf:"varint,2,opt,name=wall,proto3" json:"wall,omitempty"` // was failure due to wall?
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{5}
}

func (x *MoveResponse) GetStatus() MoveResponse_Status {
	if x != nil {
		return x.Status
	}
	return MoveResponse_SUCCESS
}

func (x *MoveResponse) GetWall() bool {
	if x != nil {
		return x.Wall
	}
	return false
}

type RevelioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position           `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Type     RevelioRequest_Tile `protobuf:"varint,2,opt,name=type,proto3,enum=labyrinth.RevelioRequest_Tile" json:"type,omitempty"`
}

func (x *RevelioRequest) Reset() {
	*x = RevelioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevelioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevelioRequest) ProtoMessage() {}

func (x *RevelioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevelioRequest.ProtoReflect.Descriptor instead.
func (*RevelioRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{6}
}

func (x *RevelioRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RevelioRequest) GetType() RevelioRequest_Tile {
	if x != nil {
		return x.Type
	}
	return RevelioRequest_EMPTY
}

type RevelioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *RevelioResponse) Reset() {
	*x = RevelioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevelioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevelioResponse) ProtoMessage() {}

func (x *RevelioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevelioResponse.ProtoReflect.Descriptor instead.
func (*RevelioResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{7}
}

func (x *RevelioResponse) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type BombardaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *BombardaRequest) Reset() {
	*x = BombardaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BombardaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BombardaRequest) ProtoMessage() {}

func (x *BombardaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BombardaRequest.ProtoReflect.Descriptor instead.
func (*BombardaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{8}
}

func (x *BombardaRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type BombardaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BombardaResponse) Reset() {
	*x = BombardaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_labyrinth_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BombardaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BombardaResponse) ProtoMessage() {}

func (x *BombardaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_labyrinth_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BombardaResponse.ProtoReflect.Descriptor instead.
func (*BombardaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_labyrinth_proto_rawDescGZIP(), []int{9}
}

func (x *BombardaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_proto_labyrinth_proto protoreflect.FileDescriptor

var file_pkg_proto_labyrinth_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x62, 0x79,
	0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x61, 0x62,
	0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x26, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x3d, 0x0a, 0x0d, 0x4c, 0x61, 0x62, 0x79, 0x72,
	0x69, 0x6e, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69,
	0x6e, 0x74, 0x68, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x22, 0x73,
	0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x62, 0x79,
	0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x32, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06, 0x0a, 0x02,
	0x55, 0x50, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x47, 0x48,
	0x54, 0x10, 0x03, 0x22, 0x96, 0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x77, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x77, 0x61, 0x6c, 0x6c,
	0x22, 0x3a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55,
	0x52, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x49, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x41, 0x54, 0x48, 0x10, 0x03, 0x22, 0x9c, 0x01, 0x0a,
	0x0e, 0x52, 0x65, 0x76, 0x65, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2f, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e,
	0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x6c,
	0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x25, 0x0a, 0x04, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x4f, 0x49, 0x4e, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x22, 0x42, 0x0a, 0x0f, 0x52,
	0x65, 0x76, 0x65, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x42, 0x0a, 0x0f, 0x42, 0x6f, 0x6d, 0x62, 0x61, 0x72, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68,
	0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x10, 0x42, 0x6f, 0x6d, 0x62, 0x61, 0x72, 0x64, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0xdf, 0x02, 0x0a, 0x10, 0x4c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x62,
	0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x2e, 0x6c, 0x61, 0x62,
	0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x6c,
	0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x4c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e,
	0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x2e, 0x6c, 0x61,
	0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e,
	0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0f, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72,
	0x69, 0x6e, 0x74, 0x68, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x1a, 0x17, 0x2e, 0x6c, 0x61, 0x62, 0x79,
	0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x6c, 0x69, 0x6f, 0x12,
	0x19, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x76, 0x65,
	0x6c, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x61, 0x62,
	0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x6c, 0x69, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x08, 0x42, 0x6f,
	0x6d, 0x62, 0x61, 0x72, 0x64, 0x61, 0x12, 0x1a, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e,
	0x74, 0x68, 0x2e, 0x42, 0x6f, 0x6d, 0x62, 0x61, 0x72, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x61, 0x62, 0x79, 0x72, 0x69, 0x6e, 0x74, 0x68, 0x2e, 0x42,
	0x6f, 0x6d, 0x62, 0x61, 0x72, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x6c, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_labyrinth_proto_rawDescOnce sync.Once
	file_pkg_proto_labyrinth_proto_rawDescData = file_pkg_proto_labyrinth_proto_rawDesc
)

func file_pkg_proto_labyrinth_proto_rawDescGZIP() []byte {
	file_pkg_proto_labyrinth_proto_rawDescOnce.Do(func() {
		file_pkg_proto_labyrinth_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_labyrinth_proto_rawDescData)
	})
	return file_pkg_proto_labyrinth_proto_rawDescData
}

var file_pkg_proto_labyrinth_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_proto_labyrinth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_proto_labyrinth_proto_goTypes = []any{
	(Move_Direction)(0),      // 0: labyrinth.Move.Direction
	(MoveResponse_Status)(0), // 1: labyrinth.MoveResponse.Status
	(RevelioRequest_Tile)(0), // 2: labyrinth.RevelioRequest.Tile
	(*Empty)(nil),            // 3: labyrinth.Empty
	(*Position)(nil),         // 4: labyrinth.Position
	(*LabyrinthInfo)(nil),    // 5: labyrinth.LabyrinthInfo
	(*PlayerStatus)(nil),     // 6: labyrinth.PlayerStatus
	(*Move)(nil),             // 7: labyrinth.Move
	(*MoveResponse)(nil),     // 8: labyrinth.MoveResponse
	(*RevelioRequest)(nil),   // 9: labyrinth.RevelioRequest
	(*RevelioResponse)(nil),  // 10: labyrinth.RevelioResponse
	(*BombardaRequest)(nil),  // 11: labyrinth.BombardaRequest
	(*BombardaResponse)(nil), // 12: labyrinth.BombardaResponse
}
var file_pkg_proto_labyrinth_proto_depIdxs = []int32{
	4,  // 0: labyrinth.PlayerStatus.position:type_name -> labyrinth.Position
	0,  // 1: labyrinth.Move.direction:type_name -> labyrinth.Move.Direction
	1,  // 2: labyrinth.MoveResponse.status:type_name -> labyrinth.MoveResponse.Status
	4,  // 3: labyrinth.RevelioRequest.position:type_name -> labyrinth.Position
	2,  // 4: labyrinth.RevelioRequest.type:type_name -> labyrinth.RevelioRequest.Tile
	4,  // 5: labyrinth.RevelioResponse.position:type_name -> labyrinth.Position
	4,  // 6: labyrinth.BombardaRequest.position:type_name -> labyrinth.Position
	3,  // 7: labyrinth.LabyrinthService.GetLabyrinthInfo:input_type -> labyrinth.Empty
	3,  // 8: labyrinth.LabyrinthService.GetPlayerStatus:input_type -> labyrinth.Empty
	7,  // 9: labyrinth.LabyrinthService.RegisterMove:input_type -> labyrinth.Move
	9,  // 10: labyrinth.LabyrinthService.Revelio:input_type -> labyrinth.RevelioRequest
	11, // 11: labyrinth.LabyrinthService.Bombarda:input_type -> labyrinth.BombardaRequest
	5,  // 12: labyrinth.LabyrinthService.GetLabyrinthInfo:output_type -> labyrinth.LabyrinthInfo
	6,  // 13: labyrinth.LabyrinthService.GetPlayerStatus:output_type -> labyrinth.PlayerStatus
	8,  // 14: labyrinth.LabyrinthService.RegisterMove:output_type -> labyrinth.MoveResponse
	10, // 15: labyrinth.LabyrinthService.Revelio:output_type -> labyrinth.RevelioResponse
	12, // 16: labyrinth.LabyrinthService.Bombarda:output_type -> labyrinth.BombardaResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_labyrinth_proto_init() }
func file_pkg_proto_labyrinth_proto_init() {
	if File_pkg_proto_labyrinth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_labyrinth_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LabyrinthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RevelioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RevelioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*BombardaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_labyrinth_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BombardaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_labyrinth_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_labyrinth_proto_goTypes,
		DependencyIndexes: file_pkg_proto_labyrinth_proto_depIdxs,
		EnumInfos:         file_pkg_proto_labyrinth_proto_enumTypes,
		MessageInfos:      file_pkg_proto_labyrinth_proto_msgTypes,
	}.Build()
	File_pkg_proto_labyrinth_proto = out.File
	file_pkg_proto_labyrinth_proto_rawDesc = nil
	file_pkg_proto_labyrinth_proto_goTypes = nil
	file_pkg_proto_labyrinth_proto_depIdxs = nil
}
