// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/docs.proto

package dpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocsService_SendMessage_FullMethodName    = "/docs.DocsService/SendMessage"
	DocsService_RegisterClient_FullMethodName = "/docs.DocsService/RegisterClient"
	DocsService_SendError_FullMethodName      = "/docs.DocsService/SendError"
	DocsService_EditDoc_FullMethodName        = "/docs.DocsService/EditDoc"
)

// DocsServiceClient is the client API for DocsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocsServiceClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageResponse, error)
	RegisterClient(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Document, error)
	SendError(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
	EditDoc(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type docsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocsServiceClient(cc grpc.ClientConnInterface) DocsServiceClient {
	return &docsServiceClient{cc}
}

func (c *docsServiceClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, DocsService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docsServiceClient) RegisterClient(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocsService_RegisterClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docsServiceClient) SendError(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DocsService_SendError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docsServiceClient) EditDoc(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocsService_ServiceDesc.Streams[0], DocsService_EditDoc_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocsService_EditDocClient = grpc.BidiStreamingClient[Message, Message]

// DocsServiceServer is the server API for DocsService service.
// All implementations must embed UnimplementedDocsServiceServer
// for forward compatibility.
type DocsServiceServer interface {
	SendMessage(context.Context, *Message) (*MessageResponse, error)
	RegisterClient(context.Context, *Message) (*Document, error)
	SendError(context.Context, *Message) (*Empty, error)
	EditDoc(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedDocsServiceServer()
}

// UnimplementedDocsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocsServiceServer struct{}

func (UnimplementedDocsServiceServer) SendMessage(context.Context, *Message) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedDocsServiceServer) RegisterClient(context.Context, *Message) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedDocsServiceServer) SendError(context.Context, *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendError not implemented")
}
func (UnimplementedDocsServiceServer) EditDoc(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Errorf(codes.Unimplemented, "method EditDoc not implemented")
}
func (UnimplementedDocsServiceServer) mustEmbedUnimplementedDocsServiceServer() {}
func (UnimplementedDocsServiceServer) testEmbeddedByValue()                     {}

// UnsafeDocsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocsServiceServer will
// result in compilation errors.
type UnsafeDocsServiceServer interface {
	mustEmbedUnimplementedDocsServiceServer()
}

func RegisterDocsServiceServer(s grpc.ServiceRegistrar, srv DocsServiceServer) {
	// If the following call pancis, it indicates UnimplementedDocsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocsService_ServiceDesc, srv)
}

func _DocsService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocsServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocsService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocsServiceServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocsService_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocsServiceServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocsService_RegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocsServiceServer).RegisterClient(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocsService_SendError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocsServiceServer).SendError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocsService_SendError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocsServiceServer).SendError(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocsService_EditDoc_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocsServiceServer).EditDoc(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocsService_EditDocServer = grpc.BidiStreamingServer[Message, Message]

// DocsService_ServiceDesc is the grpc.ServiceDesc for DocsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docs.DocsService",
	HandlerType: (*DocsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _DocsService_SendMessage_Handler,
		},
		{
			MethodName: "RegisterClient",
			Handler:    _DocsService_RegisterClient_Handler,
		},
		{
			MethodName: "SendError",
			Handler:    _DocsService_SendError_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EditDoc",
			Handler:       _DocsService_EditDoc_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/docs.proto",
}
